version: '3'

services:
  app:
    image: flexberry/ember-flexberry-stand-backend:latest
    links:
      - app-postgres-db:app-postgres-db
    ports:
      - 80:80
    environment:
      - UploadUrl=Uploads
      - BackendRoot=http://localhost
      - DefConnStr=SERVER=app-postgres-db;User ID=postgres;Password=p@ssw0rd;Port=5432;database=appdb;

  app-postgres-db:
    image: flexberry/ember-flexberry-stand-postgres:latest
    volumes:
      - DB:/var/lib/pgsql/data/
    ports:
      - 5435:5432
volumes:
  DB:
