version: '3'
services:
  app-postgres-db:
    image: "flexberry/ember-flexberry-stand-postgres:latest"
    volumes:
      - PostgresEmberFlexberryStandDB:/var/lib/pgsql/data/
    ports:
     - "5432:5432"
volumes:
  PostgresEmberFlexberryStandDB: 
