services:
  app:
    build:
      context: ..
      dockerfile: Docker/full-test-stand/Dockerfile
    image: flexberry/ember-flexberry-full-test-stand:latest
    links:
      - app-postgres-db:app-postgres-db
    ports:
      - 80:80
    environment:
      - UploadUrl=Uploads
      - BackendRoot=http://localhost
      - DefConnStr=SERVER=app-postgres-db;User ID=postgres;Password=p@ssw0rd;Port=5432;database=appdb;

  app-postgres-db:
    build:
      context: ../SQL
      dockerfile: ../Docker/SQLDocker/Dockerfile.PostgreSql
    image: flexberry/ember-flexberry-stand-postgres:latest
    volumes:
      - EmberStandDB:/var/lib/pgsql/data/
    ports:
      - 5432:5432
volumes:
  EmberStandDB:
